project_id = "qypazgkngxhazgkuevwq"

[functions.analyze-credit-assessment]
verify_jwt = true

[functions.create-daily-room]
verify_jwt = true

[functions.generate-narration]
verify_jwt = false

[functions.generate-matches]
verify_jwt = true

[functions.send-booking-email]
verify_jwt = true

[functions.send-review-request]
verify_jwt = true

[functions.copilot-chat]
verify_jwt = false

[functions.get-daily-token]
verify_jwt = true

[functions.send-confirmation-email]
verify_jwt = false

[functions.subscribe-status-notifications]
verify_jwt = false
