project_id = "qypazgkngxhazgkuevwq"

[functions.analyze-credit-assessment]
verify_jwt = true

[functions.generate-narration]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = true

[functions.send-review-request]
verify_jwt = true